title: Aplicación móvil de SocioUnido
description: Documentación de la aplicación móvil (PWA) de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/aplicacion"
