title: Aplicación móvil (PWA) de SocioUnido
description: Documentacion de la aplicación móvil (PWA) de SocioUnido
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/aplicacion"
